django/srcs/config/urls.py
from articleapp.views import ArticleListView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("account.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("projects/", include("projectapp.urls")),
    path("subscriptions/", include("subscriptionapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/srcs/projectapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "projectapp"

urlpatterns = [
    path("list/", views.ProjectListView.as_view(), name="list"),
    path("create/", views.ProjectCreateView.as_view(), name="create"),
    path("detail/<int:pk>", views.ProjectDetailView.as_view(), name="detail"),
    path("delete/<int:pk>", views.ProjectDeleteView.as_view(), name="delete"),
]

django/srcs/subscriptionapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import SubscriptionListView, SubscriptionView

app_name = "subscriptionapp"

urlpatterns = [
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("list/", SubscriptionListView.as_view(), name="list"),
]

django/srcs/articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project


# Create your models here.
class Article(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name="article", null=True)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="article", null=True)
    title = models.CharField(max_length=128, null=True)
    image = models.ImageField(upload_to="article/", null=False)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

django/srcs/projectapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=128, null=False)
    image = models.ImageField(upload_to="projects/", null=False)
    description = models.TextField(null=False)
    created_at = models.DateField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.pk}: {self.title}"

django/srcs/projectapp/forms.py
from django.forms import ModelForm

from . import models


class ProjectCreationForm(ModelForm):
    class Meta:
        model = models.Project
        fields = ["title", "image", "description"]

django/srcs/projectapp/views.py
from articleapp.models import Article
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin
from subscriptionapp.models import Subscription

from . import deco, forms, models

# Create your views here.

has_ownership = [login_required, deco.project_ownership_required]


@method_decorator(login_required, "get")
@method_decorator(login_required, "post")
class ProjectCreateView(CreateView):
    model = models.Project
    form_class = forms.ProjectCreationForm
    template_name = "projectapp/create.html"

    def form_valid(self, form):
        temp = form.save(commit=False)
        temp.owner = self.request.user
        temp.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("projectapp:detail", kwargs={"pk": self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = models.Project
    context_object_name = "target_project"
    template_name = "projectapp/detail.html"
    paginate_by = 7

    # template에 넘길 context data를 준비한다.
    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user
        if user.is_authenticated:
            sub = Subscription.objects.filter(user=user, project=project)
        else:
            sub = None
        object_list = Article.objects.filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list, subscription=sub, **kwargs)


class ProjectListView(ListView):
    model = models.Project
    context_object_name = "project_list"
    template_name = "projectapp/list.html"
    paginate_by = 20

    def get_queryset(self):
        project_list = models.Project.objects.all().order_by("title")
        return project_list


# @method_decorator(has_ownership, "get")
# @method_decorator(has_ownership, "post")
class ProjectDeleteView(DeleteView):
    model = models.Project
    context_object_name = "target_project"
    success_url = reverse_lazy("projectapp:list")
    template_name = "projectapp/delete.ㅛyhtml"

django/srcs/projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4.0rem auto;">
    <div class="mb-4">
        <h4>Create a project</h4>
    </div>
        <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="create">
        </form>
    </div>

{% endblock %}

django/srcs/projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4.0rem auto;">
    <div class="mb-4">
        <h4>Delete: {{ target_project.title }}</h4>
    </div>
        <form action="{% url 'projectapp:delete' pk=target_project.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="delete">
        </form>
    </div>

{% endblock %}

django/srcs/projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width: 700px; margin: 4.0rem auto;">
        <div>
            <h1>{{ target_project.title }}</h1>
            <h4>{{ target_project.created_at }}</h4>
        </div>

        <hr>

        <img style="width: 100%; border-radius: 1.0rem; margin: 2.0rem; object-fit: cover;"
             src="{{ target_project.image.url }}" alt="">

        <p>{{ target_project.description }}</p>

        <div class="text-center mb-3">
            {% if user.is_authenticated %}
                {% if subscription %}
                    <a href="{% url 'subscriptionapp:subscribe' %}?project_pk={{ target_project.pk }}"
                       class="btn btn-danger rounded-pill col-3">
                        Unsubscribe
                    </a>
                {% else %}
                    <a href="{% url 'subscriptionapp:subscribe' %}?project_pk={{ target_project.pk }}"
                       class="btn btn-primary rounded-pill col-3">
                        Subscribe
                    </a>
                {% endif %}
            {% endif %}
            <div>
                {% include 'snippets/list_fragment.html' with article_list=object_list %}
            </div>
            <div>
                {#                {% if user == target_project.user %}#}
                <a href="{% url 'projectapp:delete' pk=target_project.pk %}"
                   class="btn btn-danger rounded-pill col-3 mb-3">
                    Delete
                </a>
                {#                {% endif %}#}
            </div>
        </div>

        <hr>
    </div>
{% endblock %}

django/srcs/projectapp/templates/projectapp/list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container {
            padding: 0;
            margin: 0, auto;
        }

        .container div {
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1.0rem;
        }

        .container img {
            width: 7rem;
            height: 7rem;
            object-fit: cover;
            border-radius: 1.0rem;
        }

    </style>

    {% if project_list %}
        <div class="container">
            {% for project in project_list %}
                <a href="{% url 'projectapp:detail' pk=project.pk %}">
                    {% include 'snippets/card_project.html' with project=project %}
                </a>
            {% endfor %}
        </div>
        <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
        <div class="text-center">
            <h1>No projects</h1>
        </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center; max-width: 600px; margin: 4.0rem auto;">
        <a href="{% url 'projectapp:create' %}"
           class="btn btn-dark rounded-pill col-3 mb-3">
            Create a project
        </a>
    </div>

{% endblock %}