django/srcs/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "articleapp"

urlpatterns = [
    path("list/", views.ArticleListView.as_view(), name="list"),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>", views.ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>", views.ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", views.ArticleDeleteView.as_view(), name="delete"),
]

django/srcs/config/urls.py
from articleapp.views import ArticleListView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("account.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("projects/", include("projectapp.urls")),
    path("subscriptions/", include("subscriptionapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/srcs/articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project


# Create your models here.
class Article(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name="article", null=True)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="article", null=True)
    title = models.CharField(max_length=128, null=True)
    image = models.ImageField(upload_to="article/", null=False)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

django/srcs/articleapp/forms.py
from django.forms import ModelForm
from projectapp.models import Project

from django import forms

from . import models


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "editable text-left", "style": "height: auto;"}))
    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    class Meta:
        model = models.Article
        fields = ["title", "image", "project", "content"]

django/srcs/articleapp/views.py
from commentapp.forms import CommentCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.views.generic.edit import FormMixin

from . import deco, forms, models

has_ownership = [login_required, deco.article_ownership_required]


# Create your views here.


@method_decorator(login_required, "get")
@method_decorator(login_required, "post")
class ArticleCreateView(CreateView):
    model = models.Article
    form_class = forms.ArticleCreationForm
    template_name = "articleapp/create.html"

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("articleapp:detail", kwargs={"pk": self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = models.Article
    context_object_name = "target_article"
    template_name = "articleapp/detail.html"
    form_class = CommentCreationForm


@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class ArticleUpdateView(UpdateView):
    model = models.Article
    context_object_name = "target_article"
    form_class = forms.ArticleCreationForm
    template_name = "articleapp/update.html"

    def get_success_url(self):
        return reverse("articleapp:detail", kwargs={"pk": self.object.pk})


@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class ArticleDeleteView(DeleteView):
    model = models.Article
    context_object_name = "target_article"
    success_url = reverse_lazy("articleapp:list")
    template_name = "articleapp/delete.html"


class ArticleListView(ListView):
    model = models.Article
    context_object_name = "article_list"
    template_name = "articleapp/list.html"
    paginate_by = 20

    def get_queryset(self):
        article_list = models.Article.objects.all().order_by("created_at")
        return article_list

django/srcs/articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4.0rem auto;">
        <div class="mb-4">
            <h4>Create article</h4>
        </div>
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="create article">
        </form>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

django/srcs/articleapp/templates/articleapp/delete.html
y{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4.0rem auto;">
    <div class="mb-4">
        <h4>Delete: {{ target_article.title }}</h4>
    </div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="delete">
        </form>
    </div>

{% endblock %}

django/srcs/articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width: 700px; margin: 4.0rem auto;">
        <div>
            <h1>{{ target_article.title }}</h1>
            <h4>{{ target_article.writer.profile.nickname }}</h4>
        </div>

        <hr>

        <img style="width: 100%; border-radius: 1.0rem; margin: 2.0rem; object-fit: cover;"
             src="{{ target_article.image.url }}" alt="">

        <div class="text-left">{{ target_article.content | safe }}</div>

        {% if target_article.writer == user %}
            <a href="{% url 'articleapp:update' pk=target_article.pk %}"
               class="btn btn-primary rounded-pill col-3 mb-3">
                Update
            </a>

            <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-danger rounded-pill col-3 mb-3">
                Delete
            </a>
        {% endif %}
        <hr>
        {% for comment in target_article.comment.all %}
            {% include 'commentapp/detail.html' with comment=comment %}
        {% endfor %}
        {% include 'commentapp/create.html' with article=target_article %}
    </div>
{% endblock %}

django/srcs/articleapp/templates/articleapp/list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container {
            padding: 0;
            margin: 0, auto;
        }

        .container a {
            width: 45%;
            max-width: 250px;
        }

        .container div {
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1.0rem;
        }

        .container img {
            width: 100%;
            border-radius: 1.0rem;
        }

    </style>

    {% if article_list %}
        <div class="container">
            {% for article in article_list %}
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    {% include 'snippets/card.html' with article=article %}
                </a>
            {% endfor %}
        </div>
        <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
        <div class="text-center">
            <h1>No articles</h1>
        </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center; max-width: 600px; margin: 4.0rem auto;">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill col-3 mb-3">
            Create article
        </a>
    </div>

{% endblock %}

django/srcs/articleapp/templates/articleapp/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4.0rem auto;">
    <div class="mb-4">
        <h4>Update article</h4>
    </div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="update article">
        </form>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}