django/srcs/account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    path("create/", views.AccountCreateView.as_view(), name="create"),
    path("login/", LoginView.as_view(template_name="account/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("detail/<int:pk>", views.AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", views.AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", views.AccountDeleteView.as_view(), name="delete"),
]

django/srcs/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "articleapp"

urlpatterns = [
    path("list/", views.ArticleListView.as_view(), name="list"),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>", views.ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>", views.ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", views.ArticleDeleteView.as_view(), name="delete"),
]

django/srcs/config/urls.py
from articleapp.views import ArticleListView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("account.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("projects/", include("projectapp.urls")),
    path("subscriptions/", include("subscriptionapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/srcs/projectapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "projectapp"

urlpatterns = [
    path("list/", views.ProjectListView.as_view(), name="list"),
    path("create/", views.ProjectCreateView.as_view(), name="create"),
    path("detail/<int:pk>", views.ProjectDetailView.as_view(), name="detail"),
    path("delete/<int:pk>", views.ProjectDeleteView.as_view(), name="delete"),
]

django/srcs/subscriptionapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import SubscriptionListView, SubscriptionView

app_name = "subscriptionapp"

urlpatterns = [
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("list/", SubscriptionListView.as_view(), name="list"),
]

django/srcs/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}

<body style="font-family: 'MaruBuri-Light';">
{% include "header.html" %}
<hr>
{% block content %}
{% endblock %}
<hr>
{% include "footer.html" %}
</body>

</html>

django/srcs/templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>
            Announcement
        </span> |
        <span>
            Inqueries
        </span> |
        <span>
            About us
        </span>
    </div>
    <div>
        <h6 class="pragmatic_footer_logo">Pragmatic</h6>
    </div>
</div>

django/srcs/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>pinterest-tutorial</title>

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- MEDIUM EDITOR LINK -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">

    <!-- MATERIAL ICONS -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <!-- OSWALD FONT LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: MaruBuri-Bold;
            src: local('MaruBuri-Bold'), url("{% static 'fonts/MaruBuri-Bold.ttf' %}"), format("truetype");
        }

        @font-face {
            font-family: MaruBuri-ExtraLight;
            src: local('MaruBuri-ExtraLight'), url("{% static 'fonts/MaruBuri-ExtraLight.ttf' %}"), format("truetype");
        }

        @font-face {
            font-family: MaruBuri-Light;
            src: local('MaruBuri-Light'), url("{% static 'fonts/MaruBuri-Light.ttf' %}"), format("truetype");
        }

        @font-face {
            font-family: MaruBuri-Regular;
            src: local('MaruBuri-Regular'), url("{% static 'fonts/MaruBuri-Regular.ttf' %}"), format("truetype");
        }

        @font-face {
            font-family: MaruBuri-SemiBold;
            src: local('MaruBuri-SemiBold'), url("{% static 'fonts/MaruBuri-SemiBold.ttf' %}"), format("truetype");
        }
    </style>
</head>

django/srcs/templates/header.html
<div class="pragmatic_header">
    <div>
        <h1>
            PINTEREST-TUTORIAL
        </h1>
    </div>
    <div class="pragmatic_header_nav_bar">
        <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
            <span>ARTICLES</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
            <span>PROJECTS</span>
        </a>

        {% if user.is_authenticated %}
        <a href="{% url 'subscriptionapp:list' %}" class="pragmatic_header_nav">
            <span>SUBS</span>
        </a>
        {% endif %}

        {% if not user.is_authenticated %}
            <a href="{% url 'account:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>LOGIN</span>
            </a>
            <a href="{% url 'account:create' %}" class="pragmatic_header_nav">
                <span>SIGN UP</span>
            </a>
        {% else %}
            <a href="{% url 'account:detail' pk=user.pk %}" class="pragmatic_header_nav">
                <span>MY PAGE</span>
            </a>
            <form action="{% url 'account:logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="logout">
            </form>
        {% endif %}
    </div>
</div>